
use_frameworks!
pod 'MultiSlider', :path => '..'

target 'MultiSliderDemo' do
end

# workaround for IB problems with dynamic frameworks
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
        '$(FRAMEWORK_SEARCH_PATHS)'
        ]
    end
end

