excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
opt_in_rules:
  - force_unwrapping
  - explicit_init
  - overridden_super_call
  - redundant_nil_coalescing
  - nimble_operator
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - number_separator
  - prohibited_super_call
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - unneeded_parentheses_in_closure_argument
  - pattern_matching_keywords
  - literal_expression_end_indentation
  - joined_default_parameter
  - contains_over_first_not_nil
  - override_in_extension
  - single_test_class
  - sorted_first_last
  - convenience_type
  - empty_count
  - empty_string
  - toggle_bool
  - unused_private_declaration
  - identical_operands
  - array_init
  - implicit_return
  - implicitly_unwrapped_optional
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - last_where
  - redundant_type_annotation
trailing_comma:
  mandatory_comma: true
identifier_name:
  excluded:
    - i
    - x
    - y
    - dx
    - dy
    - on
line_length:
  warning: 160
  ignores_function_declarations: true
file_length:
  - 500
type_body_length:
  - 400
